# Generated by Django 6.0.2 on 2026-03-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicEngine', '0002_rename_titulo_album_name_remove_album_ano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='soundcloud_url',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.CharField(default='Artista desconhecido', max_length=200),
        ),
    ]
